add_newline = true

format = "($jobs)$directory$git_branch$git_status\n$character"

[directory]
style = "bold blue"
format = "[$path]($style) "
truncation_length = 0
truncate_to_repo = false

[git_branch]
style = "cyan"
format = "git:[$branch]($style) "

[git_status]
disabled = false
format = "[$modified$untracked]($style)"
style = "cyan"

[character]
success_symbol = "> "
error_symbol = "! "

[jobs]
symbol = '+'
number_threshold = 1
symbol_threshold = 1
